version: '2'
services:
  jhipstersampleapplicationone-postgresql:
    image: postgres:12.1
    # volumes:
    #     - ~/volumes/jhipster/jhipsterSampleApplicationOne/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=jhipsterSampleApplicationOne
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
